sudo: required
services:
  - docker

before_install:
  - docker build -t batbien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run batbien/react-test npm test -- --coverage

after_success:
  - docker build -t batbien/multi-client ./client
  - docker build -t batbien/multi-nginx ./nginx
  - docker build -t batbien/multi-server ./server
  - docker build -t batbien/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push batbien/multi-client
  - docker push batbien/multi-nginx
  - docker push batbien/multi-server
  - docker push batbien/multi-worker
