version: "3"
services:
  redis:
    image: "redis:latest"
  postgres:
    image: "postgres:latest"
  nginx:
    build:
      context: "./nginx"
    ports:
        - "3000:80"
  client:
    build:
      context: "./client"
    volumes:
        - /app/node_modules
  api:
    build:
      context: "./server"
    volumes:
        - /app/node_modules
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGHOST=postgre
        - PGPORT=5432
        - PGUSER=postgres
        - PGPASSWORD=postgres_password
  worker:
    build:
      context: "./worker"
    volumes:
        - /app/node_modules
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
       

